### PR TITLE
adding my script

### PR DESCRIPTION
**Pull request by ahmad-boop**

### CODE REVIEW

**Comment by harryWonder** [comment]
>Sorry Ahmad. Can you delete the HNGi7_Titans_Task2 folder, the Scripts folder and this file **Ahmad_Ayub-hng04340.js**. Please include the file inside of the scripts folder

**Comment by ahmad-boop** [comment]
how?

**Comment by elizabethadegbaju** [comment]
sorry for the bother but please create a new PR and add your file inside the `scripts` folder. Do not add anything else to the repo and do not create a `Scripts` folder like you just did

**Comment by ahmad-boop** [comment]
am I done it?

**Pull request closed without merging**
