### PR TITLE
Update charles.js

### PR DESCRIPTION
**Pull request by mancharlie47**

### CODE REVIEW

**Comment by timothymayor** [comment]
your script has a merge conflict... please update! and why is your script - script/charles.js? I don't get it...

**Comment by mancharlie47** [comment]
how  can i resolve conflicts

**Comment by elizabethadegbaju** [comment]
Hi, this pull rewuest is going to delete some other peoples files so I will have to close it. message me now and I will put you through creating your next pull request. my username is elizabeth

**Comment by mancharlie47** [comment]
please i will love to create a pull my request what should i do

**Pull request closed without merging**
